namespace SpriteKind {
    export const tårne = SpriteKind.create()
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . f . . . . . . . 
        . . . . . . . f d f . . . . . . 
        . . . . . . . . f . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, mySprite2, 0, 50)
})
let projectile2: Sprite = null
let projectile: Sprite = null
let tåren: Sprite = null
let mySprite2: Sprite = null
mySprite2 = sprites.create(img`
    . . . . . . f f f f . . . . . . 
    . . . . f f f 2 2 f f f . . . . 
    . . . f f f 2 2 2 2 f f f . . . 
    . . f f f e e e e e e f f f . . 
    . . f f e 2 2 2 2 2 2 e e f . . 
    . . f e 2 f f f f f f 2 e f . . 
    . . f f f f e e e e f f f f . . 
    . f f e f b f 4 4 f b f e f f . 
    . f e e 4 1 f d d f 1 4 e e f . 
    . . f e e d d d d d d e e f . . 
    . . . f e e 4 4 4 4 e e f . . . 
    . . e 4 f 2 2 2 2 2 2 f 4 e . . 
    . . 4 d f 2 2 2 2 2 2 f d 4 . . 
    . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
    . . . . . f f f f f f . . . . . 
    . . . . . f f . . f f . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(mySprite2)
scene.cameraFollowSprite(mySprite2)
tiles.setCurrentTilemap(tilemap`level1`)
for (let Gul_tilemap of tiles.getTilesByType(assets.tile`gul_tile`)) {
    tåren = sprites.create(img`
        ........................................
        ........................................
        ........................................
        ........................................
        ........................................
        ........................................
        ........................................
        .....dddddddddddddddddddddddddddddd.....
        .....dddddddddddddddddddddddddddddd.....
        .....dddddddddddddddddddddddddddddd.....
        .......ddd..ddd...ddd...ddd...ddd.......
        .......ddd..ddd...ddd...ddd...ddd.......
        .......ddd..ddd...ddd...ddd...ddd.......
        ....bbbddd..ddd...ddd...ddd...dddbbb....
        ....bbbddddddddddddddddddddddddddbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbdddbbbbbbbbbbbbbbbdddbbbbb....
        ....bbbbbbdddbbbbbbbbbbbbbbbdddbbbbb....
        ....bbbbbbdddbbbbbbbbbbbbbbbdddbbbbb....
        ....bbbdddfffdddbbbbbbbbbdddfffdddbb....
        ....bbbdddfffdddbbbbbbbbbdddfffdddbb....
        ....bbbdddfffdddbbbbbbbbbdddfffdddbb....
        ....bbbbbbdddbbbbbbbbbbbbbbbdddbbbbb....
        ....bbbbbbdddbbbbbbbbbbbbbbbdddbbbbb....
        ....bbbbbbdddbbbbbbbbbbbbbbbdddbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
        ..dddddddddddddddddddddddddddddddddddd..
        ..dddddddddddddddddddddddddddddddddddd..
        dddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddd
        `, SpriteKind.tårne)
    tåren.setPosition(Gul_tilemap.x, Gul_tilemap.y)
}
game.onUpdate(function () {
	
})
game.onUpdateInterval(200, function () {
    for (let tåren of sprites.allOfKind(tåren)) {
        projectile2 = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . f . . . . . . . 
            . . . . . . . f d f . . . . . . 
            . . . . . . . . f . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, tåren, 50, 50)
    }
})
